### PR TITLE
Fix build dependencies for 2.8.4-imos branch

### PR DESCRIPTION
**Pull request by anguss00**

### CODE REVIEW

**Comment by julian1** [comment]
@anguss00 I believe @jonescc changed the build dependencies to include the -imos bit to distinguish our local changes from upstream geoserver. Otherwise any dependent project (geoserver_build) will pull in the wrong ones. 

I suggested that the repo of the dependent be changed, but apparently that's bad practice.

**Comment by anguss00** [comment]
Ok, but I had to change the version dependencies to remove the imos component as geoserver wouldn't build on jenkins or locally due to all of the linked version numbers throughout the poms... Not sure how else we deal with that.

**Comment by julian1** [comment]
> The issue I was seeing was maven searching for an artifact version 2.8.4-imos and failing to find it on boundlessrepo

In geoserver_build? Isn't that the desired behavior.  To use our locally built artifacts in preference to upstream ones?

**Comment by anguss00** [comment]
Ah ok, sorry I misunderstood. How are we going to build and serve all of those dependencies though?

**Comment by julian1** [comment]
I'd strongly suggest avoiding adding Jenkins as an extra variable for the moment. Try to get geoserver built locally with the imos extension. Then change geoserver-build to use the imos extended artifacts, by changing the artifact names, and adding a file type repository.

**Comment by jonescc** [comment]
This looks like its been superceded by subsequent pull requests

**Pull request closed without merging**
