### PR TITLE
optionally disable synchronous wps

### PR DESCRIPTION
**Pull request by julian1**

### CODE REVIEW

**Comment by danfruehauf** [comment]
Is this something you plan on submitting upstream?

**Comment by julian1** [comment]
sure, but i want someone to review first.

**Comment by danfruehauf** [comment]
Yep. So I have a couple of comments on that:
1. I think better if the checkbox is to enable synchronous rather to disable, but not sure. Having checkbox with negatives is usually not the best thing
2. Some tests could probably be added I believe, so it will be accepted by upstream

**Comment by julian1** [comment]
I considered the negative logic, and decided it should reflect the action we want - ie to disable synchronous wps.  To me, it doesn't make sense to have an enableWPS checkbox when that behavior is already indicated and required by the wps protocol. On that basis I chose to go with Disable rather than Enable for both java naming and ui components.

I'm happy to add tests when we want to push upstream, but would prefer to address more obvious issues as a priority.

**Comment by danfruehauf** [comment]
Apart from that I couldn't find anything that stands out - looks good to me.

**Comment by julian1** [comment]
I had a look and there aren't any behavior tests of the WPSExecutionManager which is where the process handling logic is. 

I'm reluctant to add tests, when it's not already under test, given that the functionality is spread across many collaborator classes.

**Comment by danfruehauf** [comment]
Fair enough. So I think submit this PR. Unless you want me to merge it also here?

**Comment by julian1** [comment]
Whether they accept the changes or not, they're not going to flow back to us immediately as a stable release version. If we want a geoserver to meet marvl needs, then we should be using our version which means merging outstanding PRs.

**Pull request merged**
